"""create volume related tables

Revision ID: 776ca4f238c3
Revises:
Create Date: 2018-07-13 23:56:22.753180

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "776ca4f238c3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
    )

    op.create_table(
        "volume_author",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volume_author")),
    )

    op.create_table(
        "volume",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("vol_number", sa.Text(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("prev", sa.Integer(), nullable=False),
        sa.Column("next", sa.Integer(), nullable=False),
        sa.Column("cover", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["volume_author.id"],
            name=op.f("fk_volume_author_id_volume_author"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volume")),
    )

    op.create_table(
        "volume_tag",
        sa.Column("volume_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("fk_volume_tag_tag_id_tag")
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"], ["volume.id"], name=op.f("fk_volume_tag_volume_id_volume")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("volume_tag")
    op.drop_table("volume")
    op.drop_table("volume_author")
    op.drop_table("tag")
    # ### end Alembic commands ###
